### ISSUE TITLE
Troubleshooting setup

### ISSUE THREAD

**Issue by MisterJimson** [runs-on/runs-on#27]
Hello!

I'm trying to see if runs-on would fit our needs and I'm having a bit of trouble getting started. I did not get the "RunsOn Application is online" email.

Reviewing the logs for RunsOnService I see the following.

```
03-05-2024 04:16:08 PM AccessDenied: User: arn:aws:sts::066661520573:assumed-role/runs-on-RunsOnServiceRole-tWs7cLY5ltn3/5c525838-279e-4302-80c7-aecb074ef4db is not authorized to perform: cloudformation:DescribeStacks on resource: arn:aws:cloudformation:us-east-1:066661520573:stack/runs-on/3c011e80-db35-11ee-adc6-0efc3927b4df because no identity-based policy allows the cloudformation:DescribeStacks action
03-05-2024 04:16:08 PM     at throwDefaultError (/usr/src/app/node_modules/@smithy/smithy-client/dist-cjs/index.js:838:20)
03-05-2024 04:16:08 PM     at /usr/src/app/node_modules/@smithy/smithy-client/dist-cjs/index.js:847:5
03-05-2024 04:16:08 PM     at de_CommandError (/usr/src/app/node_modules/@aws-sdk/client-cloudformation/dist-cjs/index.js:3167:14)
03-05-2024 04:16:08 PM     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
03-05-2024 04:16:08 PM     at async /usr/src/app/node_modules/@smithy/middleware-serde/dist-cjs/index.js:35:20
03-05-2024 04:16:08 PM     at async /usr/src/app/node_modules/@aws-sdk/client-cloudformation/node_modules/@aws-sdk/middleware-signing/dist-cjs/index.js:192:18
03-05-2024 04:16:08 PM     at async /usr/src/app/node_modules/@smithy/middleware-retry/dist-cjs/index.js:320:38
03-05-2024 04:16:08 PM     at async /usr/src/app/node_modules/@aws-sdk/client-cloudformation/node_modules/@aws-sdk/middleware-logger/dist-cjs/index.js:33:22
03-05-2024 04:16:08 PM     at async setup (/usr/src/app/src/config.js:14:20)
03-05-2024 04:16:08 PM     at async Object.synchronize (/usr/src/app/src/config.js:43:3) {
03-05-2024 04:16:08 PM   '$fault': 'client',
03-05-2024 04:16:08 PM   '$metadata': {
03-05-2024 04:16:08 PM     httpStatusCode: 403,
03-05-2024 04:16:08 PM     requestId: '197e3088-d894-48af-a37f-e63befc047dc',
03-05-2024 04:16:08 PM     extendedRequestId: undefined,
03-05-2024 04:16:08 PM     cfId: undefined,
03-05-2024 04:16:08 PM     attempts: 1,
03-05-2024 04:16:08 PM     totalRetryDelay: 0
03-05-2024 04:16:08 PM   },
03-05-2024 04:16:08 PM   Type: 'Sender',
03-05-2024 04:16:08 PM   Code: 'AccessDenied'
03-05-2024 04:16:08 PM }
03-05-2024 04:16:08 PM Node.js v20.11.1
```

**Comment by MisterJimson** [comment]
Nevermind this was me being stupid. I attempted to reuse the runs-on CloudFormation template to a second stack.

**Comment by crohr** [comment]
@MisterJimson Hi, happy to hear you managed to fix it
